-- Add columns for deterministic match scoring
-- skill_aliases: maps each user skill to semantic aliases (generated by AI at profile save)
-- experience_categories: job categories derived from work history (generated by AI at profile save)

ALTER TABLE public.jobseeker_profiles
  ADD COLUMN IF NOT EXISTS skill_aliases jsonb DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS experience_categories text[] DEFAULT NULL;

COMMENT ON COLUMN public.jobseeker_profiles.skill_aliases IS 'AI-generated semantic skill aliases, e.g. {"Welding": ["Metal Fabrication", "Arc Welding"]}';
COMMENT ON COLUMN public.jobseeker_profiles.experience_categories IS 'AI-derived job categories from work history, e.g. {"trades", "energy"}';
